version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "document-mgmt-sol"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7hz4nlxbd732"
s3_prefix = "document-mgmt-sol"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
